# Site Settings
baseurl: 		""
title: 			Nicolas Grangier

name: 			Inst<i>ants</i>
description: 	Welcome to my full static personal photography blog
url: 			"http://localhost:4000"

paginate: 		3
paginate_path: 	"blog/page:num"

twitter: 		XNcow
email: 			me@nicolas-grangier.com

disqus: 		your_disqus_shortname
analytics: 		UA-XXXXXXX-Y

copyright: 		Copyright 2015 Nicolas Grangier.	

# Build Settings
permalinks: 	pretty